export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  VIEW_CATEGORIES: 'VIEW_CATEGORIES',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  VIEW_ORDERS: 'VIEW_ORDERS',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  VIEW_COUPONS: 'VIEW_COUPONS',
  MANAGE_COUPONS: 'MANAGE_COUPONS',
  VIEW_REVIEWS: 'VIEW_REVIEWS',
  MANAGE_REVIEWS: 'MANAGE_REVIEWS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_RESTAURANT_SETTINGS: 'MANAGE_RESTAURANT_SETTINGS',
  MANAGE_PAYMENT_SETTINGS: 'MANAGE_PAYMENT_SETTINGS',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  SUPER_ADMIN_ACCESS: 'SUPER_ADMIN_ACCESS'
};

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  RESTAURANT_OWNER: 'restaurant_owner',
  CUSTOMER: 'customer'
};

export const normalizeRole = (role) => {
  if (!role) return ROLES.CUSTOMER;
  const cleanRole = String(role).toLowerCase().trim();
  if (cleanRole === 'admin') return ROLES.RESTAURANT_OWNER;
  if (cleanRole === 'user') return ROLES.CUSTOMER;
  if (Object.values(ROLES).includes(cleanRole)) return cleanRole;
  return ROLES.CUSTOMER;
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.RESTAURANT_OWNER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_COUPONS,
    PERMISSIONS.MANAGE_COUPONS,
    PERMISSIONS.VIEW_REVIEWS,
    PERMISSIONS.MANAGE_REVIEWS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_RESTAURANT_SETTINGS,
    PERMISSIONS.MANAGE_PAYMENT_SETTINGS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY
  ],
  [ROLES.CUSTOMER]: []
};

export const hasPermission = (role, permission) => {
  const normRole = normalizeRole(role);
  const permissions = ROLE_PERMISSIONS[normRole] || [];
  return permissions.includes(permission);
};
